apiVersion: v1
kind: Secret
metadata:
  name: pgsql
type: Opaque
data:
  connection_string: cG9zdGdyZXNxbDovL2NhbmRpZGF0ZTpwb3N0Z3Jlc0BteXJkcy5jcjczd2Z3aGhtNmUuZXUtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29tOjU0MzIvbXlkYg==
